### ISSUE TITLE
Resetting filter rows

### ISSUE THREAD

**Issue by ahmedfsalhin** [plotly/dash-table-experiments#2]
Amazing to see these experiments!

An issue is that the FILTER ROWS doesn't reset after search. The following steps are to reproduce the issue:

1- Build the table with multiple columns.
2- Use FILTER ROWS to filter the table by a value of one column.
3- Press the FILTER ROWS to show the filtered table without the search boxes.
4- The only way to restore the the unfiltered table is to refresh the page as the search boxes doesn't hold the filtering value.

Let me know if I am missing something. Thanks J

**Comment by chriddyp** [comment]
Thanks for reporting @ahmedfsalhin ! This was finally fixed in #4 :)

**Comment by popes01a** [comment]
Hello, 

I recently came across the same issue, using the latest version of dash-table-experiments. 

In the example below, if I filter by one column and then hide the search boxes, these still do not remember the value I filtered by. If I try to filter this further, it seems to apply the new filter on top of the old one, so I'm assuming it does store the old filter but it does not display it. You can display all the data by trying to filter on the same column again and then deleting your filter, or by refreshing the page. 

![filters persistence dash-table-experiments](https://user-images.githubusercontent.com/31436997/42451428-264479ca-837f-11e8-8895-19e5394227e7.gif)

As far as I can tell this is the same issue raised above. Not sure if the bug was reintroduced in a later commit or if I'm doing something wrong. The code I used for this is the example provided in this repo ([usage-callback.py](https://github.com/plotly/dash-table-experiments/blob/master/usage-callback.py)). 

Thanks, 
Andra
